version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      # rye 공식 설치
      - curl -sSf https://rye-up.com/get | bash
      - source "$HOME/.rye/env"

  pre_build:
    commands:
      - cd backend
      - rye sync    # 프로젝트 의존성 설치
      - rye export -f requirements.txt > requirements.txt    # EB 배포용 requirements.txt 생성

  build:
    commands:
      - rye build   # 프로젝트 빌드

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - backend/**/*              # backend 폴더의 모든 파일
    - backend/.ebextensions/**/* # Elastic Beanstalk 설정
  discard-paths: no